### ISSUE TITLE
Bibles are not current

### ISSUE THREAD

**Issue by deferredreward** [bible-technology/scribe-scripture-editor#122]
The TNs, TWs, etc seem to point to the latest unfoldingWord resources, but the Bibles available are outdated, not being updated versions. 
These are the Bibles that should be available:
https://git.door43.org/unfoldingWord/en_ult/releases
https://git.door43.org/unfoldingWord/en_ust/releases

**Comment by vipinpaul** [comment]
Added aligned bible support in 0.5.4
