### ISSUE TITLE
Button name change: Cloud Sync and Offline Sync

### ISSUE THREAD

**Issue by selvabenz** [bible-technology/scribe-scripture-editor#126]
There is a suggestion from the team (Birch, Bincy, and Rina ma'am) to change the following button names: Cloud Sync and Offline Sync.

**Comment by vipinpaul** [comment]
Joel Mathew's suggestions:
- Change the Sync icon
- CLOUD SYNC button -> Save to Cloud
- OFFLINE SYNC button -> Save to Computer
- SYNC label -> Projects on my Computer
- CLOUD PROJECTS label -> Projects on Cloud
- Gitea Project button -> {username}
- scribe Project label-> Projects
- LAST SYNC label -> Last Downloaded
![image](https://github.com/bible-technology/scribe-scripture-editor/assets/37212471/99bf52ee-0e79-44d2-a408-bca4aaea394f)
