### ISSUE TITLE
Audio flavor: Provision for bigger wave form with editing options

### ISSUE THREAD

**Issue by selvabenz** [bible-technology/scribe-scripture-editor#151]
- In the audio toolbar waveform preview could be bigger than the current size
-  Adding/inserting  silence at the beginning and the end
**Editing options** 

For Phase 2
- Trimming provision 
- Timestamp correction options

**Comment by sijumoncy** [comment]
- #156 : Changed Waveform size

**Comment by selvabenz** [comment]
For Phase 2

- Adding/inserting silence at the beginning and the end
- Editing options
- Trimming provision
- Timestamp correction options

These requirements have been attached to #143
