### ISSUE TITLE
Proposal for better About text

### ISSUE THREAD

**Issue by yakob-aleksandrovich** [bible-technology/scribe-scripture-editor#231]
The original About text has some textual issues. Here is my proposal.

---

Scribe Scripture is a standalone desktop application that aims to be a friendly companion to the Bible Translator. Scribe is a basic USFM editor and capable of importing and exporting of USFM files. It has handy features like color-coded diffs across imported texts for comparison between revisions, search and replace and export to formatted HTML. Scribe Scripture includes the capability for syncing data with online repositories.

Scribe Scripture is licensed under the MIT license.

---

**Comment by selvabenz** [comment]
@joelthe1 Could you review this text?

**Comment by joelthe1** [comment]
Thanks @yakob-aleksandrovich for sharing the suggestion!

@selvabenz Here is a slightly modified version that more closely resembles the current state of the app:
```
Scribe Scripture Editor is a free and open-licensed desktop application that is designed to support the Bible translator with drafting and checking scripture in both text and audio formats as well as provides support for translating Open Bible Stories in different modes. The features include multi-project support, revision control (cloud sync), audio recording and seamless basic USFM editing. It has a modular architecture and is poised to grow and support the evolving needs on the ground.
```

**Comment by selvabenz** [comment]
Thank you @joelthe1 for the text. I am replacing the text in the About page.

**Comment by yakob-aleksandrovich** [comment]
Great change! One grammatical error that I would like to point out: 

"... as well as provides support ..." should be ... "as well as providing support ". For the rest, :+1:

**Comment by joelthe1** [comment]
I cannot assert if that is indeed a grammatical error but I am not opposed to the change. Thanks!

**Comment by yakob-aleksandrovich** [comment]
Apparently, the change is not reflected in the About page of 0.5.5
