### ISSUE TITLE
UI - Inconsistency in the left-side bar highlights

### ISSUE THREAD

**Issue by selvabenz** [bible-technology/scribe-scripture-editor#247]
**Need to be fixed by the UI team @arpitjacob** 

On a small screen, the project highlight (active) is shrinking the left bar. whereas, other pages looks fine. 
![image](https://github.com/bible-technology/scribe-scripture-editor/assets/121541505/9d8fe2f7-3a0b-4802-9dd5-ecfa89400a9f)

![image](https://github.com/bible-technology/scribe-scripture-editor/assets/121541505/2fad2c06-4529-4a3e-ba84-2ba7a4f40739)

**About page adapts to the previous page's screen**
![image](https://github.com/bible-technology/scribe-scripture-editor/assets/121541505/a147c30b-1787-4c30-a30d-9303f9bc5314)

![image](https://github.com/bible-technology/scribe-scripture-editor/assets/121541505/2d5ae361-1602-46e7-90f7-82e57d280c9f)

**Comment by vipinpaul** [comment]
Fixed in 0.5.6
