### ISSUE TITLE
The about text has not changed

### ISSUE THREAD

**Issue by yakob-aleksandrovich** [bible-technology/scribe-scripture-editor#270]
The About text as discussed in [here](https://github.com/bible-technology/scribe-scripture-editor/issues/231) is not included in version 0.5.5. It is still displaying the old text

![image](https://github.com/bible-technology/scribe-scripture-editor/assets/16293781/e5951885-a129-4d09-a928-09cbb86c079d)

**Comment by selvabenz** [comment]
Sorry @yakob-aleksandrovich, We thought you were talking about the GitHub page therefore we changed it there. Now it is clear that where you wanna change, this change will be reflected in the coming release. Thanks for checking and informing.

**Comment by selvabenz** [comment]
The About text has been changed as suggested.

![image](https://github.com/bible-technology/scribe-scripture-editor/assets/121541505/ec317310-fb86-460b-b695-03cd4e61e3b8)
