### ISSUE TITLE
Neither Xenizo’s Translation Questions in French (nor unfoldingWord’s in English) are showing up in Scribe

### ISSUE THREAD

**Issue by jgonz3** [bible-technology/scribe-scripture-editor#277]
# Steps:
1. Open a Bible translation project
2. Add a column in order to add a resource next to the text to translate
3. Select the subcategory “Translation Questions”
4. Search for “fr”
5. The result set does not contain _Xenzio_’s “Translation Questions”

Similarly, searching for “en” won't yield results, although _unfoldingWord_’s “Translation Questions” should be found.

# Screen captures
## _Xenzio_’s “Translation Questions” on DCS – 2023-12-11 at 16:37:50
<img width="933" alt="_Xenzio_’s “Translation Questions” on DCS – 2023-12-11 at 16:37:50" src="https://github.com/bible-technology/scribe-scripture-editor/assets/51118271/dec829d1-72f8-482d-89d7-40746da03205">
## Scribe’s “Translation Questions” screen prior to searching – 2023-12-11 at 16 38 19
<img width="933" alt="Scribe’s “Translation Questions” screen prior to searching – 2023-12-11 at 16 38 19" src="https://github.com/bible-technology/scribe-scripture-editor/assets/51118271/a9f4df9d-3de2-40b5-8b00-730f9f58aeb9">
## Scribe’s “Translation Questions” screen after searching “fr” – 2023-12-11 at 16 38 40
<img width="933" alt="Scribe’s “Translation Questions” screen after searching “fr” – 2023-12-11 at 16 38 40" src="https://github.com/bible-technology/scribe-scripture-editor/assets/51118271/4fc2c6ba-2de9-499f-b76f-1f5264f1f310">
## _unfoldingWord_’s “Translation Questions” on DCS – 2023-12-11 at 16 37 57
<img width="933" alt="_unfoldingWord_’s “Translation Questions” on DCS – 2023-12-11 at 16 37 57" src="https://github.com/bible-technology/scribe-scripture-editor/assets/51118271/b112e0fe-bd82-43bb-9493-34b0aa8e2ca1">
## Scribe’s “Translation Questions” screen after searching “en” – 2023-12-11 at 16 38 26
<img width="933" alt="Scribe’s “Translation Questions” screen after searching “en” – 2023-12-11 at 16 38 26" src="https://github.com/bible-technology/scribe-scripture-editor/assets/51118271/826c88f3-3ad2-46af-9ee3-8bdc1d420bff">

**Comment by selvabenz** [comment]
@jgonz3 we are working on this issue. There are some conflicts/issues on the repo at Door43. Both English and French are appearing with the same language tag. 
![image](https://github.com/bible-technology/scribe-scripture-editor/assets/121541505/3142d567-435f-41f0-9ed5-665c87aefe4d)


I like to introduce a new feature called **Upload help resources**. This would allow you to upload downloaded Help Resources from Door43. TN TW, TQ and TA with valid manifest.yaml are the supported resources. Any mentioned Help Resources which is not available at the Scribe can be accessed using this feature. 

To Upload Help Resources

- Open the desired project from the project page
- An editor pane will open
- Click the **Layout** icon at the top left of the editor pane to add a layout for the reference resource
- Click the **Resource Selector** or **Load a Module** icon on the new layout
- A Resources pane will open, displaying a list of available resources
- Select the **Upload Help Resources** button from the list
- In the **Collection** tab click on Select Folder
- Select a Folder with valid manifest.yaml from local drive to upload
- Click on Upload
- The uploaded file will appear in the relevant resource section under the **Downloaded Resources** section with the **Uploaded** tag.

**Comment by jgonz3** [comment]
Awesome!
With that, I will check be checking on my side to see if I can spot a problem within the files.
Thanks Benz.

**Comment by jgonz3** [comment]
Come to think of it, the door43-catalog resource (in French) that is showing in Scribe is in the MD format, whereas both the Xenizo (for French) and unfoldingWord resources (for English) are in TSV format.
Which format is the correct one to use?

**Comment by jgonz3** [comment]
Hi!
We manually fixed the manifest.yaml file and uploaded it from the disk and it works. Thanks for the workaround.
![image](https://github.com/bible-technology/scribe-scripture-editor/assets/51118271/bc9a603c-f7b4-4c84-9e08-b64caf63fb71)
![image](https://github.com/bible-technology/scribe-scripture-editor/assets/51118271/473b6f36-e4b9-4732-8597-eb9fa4eb5857)
That said, keep us updated when your fix is ready ;-)
