### ISSUE TITLE
Is it possible to keep the menus highlighted based on the flavor in the resource selection pane?

### ISSUE THREAD

**Issue by selvabenz** [bible-technology/scribe-scripture-editor#34]
The image representation is given below:
While OBS flavor is selected, in the resource selection window the OBS menu should be highlighted. Do the same for the other flavors too.

![Screenshot from 2023-05-26 11-45-16](https://github.com/bible-technology/scribe-scripture-editor/assets/121541505/ccf5dbdf-ec4c-493a-b452-0f3af524c900)

**Comment by vipinpaul** [comment]
#merged
