### ISSUE TITLE
Support Translation Word Links only

### ISSUE THREAD

**Issue by joelthe1** [bible-technology/scribe-scripture-editor#353]
Remove translation words as a resource and keep only the links which are capable of syncing with the user text position.

**Comment by selvabenz** [comment]
1. Removed translation words as a resource in Bible and OBS
2. Words are syncing with the user text position in Bible and OBS

![image](https://github.com/user-attachments/assets/8b071e85-2ad0-4e5f-9c59-6e85e40b0e6d)
![image](https://github.com/user-attachments/assets/3e869418-fb90-479d-9a8c-dd50bc47e7aa)
![image](https://github.com/user-attachments/assets/01b1628d-8242-4552-af4f-6804ab102013)

@vipinpaul, This PR is working as expected, This PR can be merged.
