### ISSUE TITLE
RTL is loading LTR layout in OBS flavor

### ISSUE THREAD

**Issue by selvabenz** [bible-technology/scribe-scripture-editor#55]
**RTL is loading LTR layout in OBS flavor**

- Recreation steps  

1. Your Profile 
2. Select the App language as Farsi and save 
3. Go to the project page and create an OBS project 
4. Select Target Language as Persian (Farsi) 
5. Click the created project  
6. It loads the LTR layout in the editor pane

**Comment by vipinpaul** [comment]
done
