### ISSUE TITLE
Non-functional buttons on the editor pane in the Bible Translation pane

### ISSUE THREAD

**Issue by selvabenz** [bible-technology/scribe-scripture-editor#57]
- [x] The lock button is not working 
- Recreation steps 
1. In Bible translation editor pane, the lock button is not clickable 

- [ ] The bookmark is not working 
- Recreation steps 
1. In Bible translation editor pane, the bookmark button is not clickable 

- [x] The Blocks section button is not functional
- Recreation steps  
1. Split into blocks and collapse blocks button is clickable 
2. While the collapse button is active the title and chapter title disappear and the hash # sign appears along with the

**Comment by vipinpaul** [comment]
Closing this issue because we have created a new issue for Bookmarks #264
