### ISSUE TITLE
Offline Merge - Collaborative Editing

### ISSUE THREAD

**Issue by BincyJ** [bible-technology/scribe-scripture-editor#68]
Ability for multiple editors working on a single project at the same time using different computers to merge their work to the same single project for checking and revising each other's work. [Browse mock ups](https://app.moqups.com/dOibMyiwp1b2WDBFK9GUAM0oyD5J3POO/view/page/a60b63f8a) and expected user flow [video](https://drive.google.com/file/d/12dj5WbH7r4Kp-KP9CJxtRc-Z05tLlQiK/view?usp=drive_link)

UseCase: Editors in rural African regions working on a single OBS story want to collaboratively edit, check each other's work and complete  a single OBS story while remaining offline.

**Comment by sijumoncy** [comment]
- [x] OBS

**Comment by vipinpaul** [comment]
OBS offline merge is done.
